language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt -r requirements-dev.txt
  - pip install coveralls
script:
  - make tests
after_success:
  - coveralls
